### ISSUE TITLE
Make a android version 

### ISSUE THREAD

**Issue by ori324** [haruair/Koala-Hates-Rain#1]
Make a android version

**Comment by haruair** [comment]
You can do if you want :)

**Comment by ori324** [comment]
How

‏בתאריך יום רביעי, 21 בינואר 2015, Edward Kim notifications@github.com
כתב:

> You can do if you want :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/haruair/Koala-Hates-Rain/issues/1#issuecomment-70838368
> .

## 

נשלח מ-Gmail לנייד

**Comment by haruair** [comment]
@ori324 https://developers.google.com/games/services/android/quickstart probably?
